// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJefjJyWkjuIww867xg1piM00c4Xv1tQ',
    appId: '1:309867412291:web:ccf8b4c73cc50512200df6',
    messagingSenderId: '309867412291',
    projectId: 'w4-firebase',
    authDomain: 'w4-firebase.firebaseapp.com',
    storageBucket: 'w4-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KvaAPfHZCDaEF6yfYCXMB7b-kZ_DBNk',
    appId: '1:309867412291:android:67d2538751bcc35d200df6',
    messagingSenderId: '309867412291',
    projectId: 'w4-firebase',
    storageBucket: 'w4-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByxHb1Wl6CjjN1k0L_iHSF1O4tKcrMjC8',
    appId: '1:309867412291:ios:fd53728bf44cb338200df6',
    messagingSenderId: '309867412291',
    projectId: 'w4-firebase',
    storageBucket: 'w4-firebase.firebasestorage.app',
    iosBundleId: 'com.example.w430Takdanai',
  );
}
